### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by RAS111** [RamiroRiggeri/desafio-m5#1]
Las imágenes te tapan todo el botón que dice empezar y dificultan el poder jugar, tenes que rebuscártela para jugar y no tendría que ser así, en resoluciones de 1024 o 1366 pasan estas cosas, fíjate si lo podes solucionar.

Saludos.

**Comment by RamiroRiggeri** [comment]
Gracias, ahí hice algunos cambios para mejorar como se ve en resoluciones bajas.
