### ISSUE TITLE
Feedback #2

### ISSUE THREAD

**Issue by Alvax10** [RamiroRiggeri/desafio-m5#3]
Buenass rami! Felicidades por llegar al desafío final del módulo 5! Tengo un par de cositas que comentarte:

Fijate que en la página principal en mi pantalla las manos casi que tapan el boton de jugar, estoy en pantalla de notebook para que te hagas una idea, adjunto foto:

![Screenshot from 2022-07-06 15-43-32](https://user-images.githubusercontent.com/64299010/177620810-159856ed-e6ac-4198-8456-25dd43acf4c4.png)

Me parece bastante interesante el contador de empates que añadiste, pudiste haber puesto que no le sume ningun punto a nadie pero elegiste este camino bastante interesante, la verdad que me gustó:

![Screenshot from 2022-07-06 15-43-54](https://user-images.githubusercontent.com/64299010/177621016-aa991b39-3330-4132-8bb6-9bac7bd592a4.png)

No tengo nada más para decir que la parte visual de la página que comente al principio, asique te diría que corrigas eso nomás, pero de mi parte, el desafío está aprobado! Suerte en el siguiente módulo! 🥳 🚀

**Comment by RamiroRiggeri** [comment]
Ahí lo corregí! Me lo había comentado uno de los chicos pero se ve que no se había actualizado el build y por lo tanto el gh pages. Le agregué un media query para cambiar según la altura de la página porque en mi monitor no lo lograba visualizar.

Gracias!
